### ISSUE TITLE
Rune generated return types are any

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#985] opened 2023-05-10 18:17 UTC
```ts
export declare class Rune<out T, out U = never> {
    readonly _prime: (batch: Batch) => Run<T, U>;
    private _;
    constructor(_prime: (batch: Batch) => Run<T, U>);
    static new<T, U, A extends unknown[]>(ctor: new (batch: Batch, ...args: A) => Run<T, U>, ...args: A): Rune<T, U>;
    run(batch?: Batch): Promise<T>;
    iter(batch?: Batch): AsyncGenerator<Awaited<T>, void, unknown>;
    static constant<T>(value: T): any;
    static resolve<V>(value: V): Rune.ValueRune<Rune.T<V>, Rune.U<V>>;
    static str<X>(strings: TemplateStringsArray, ..._values: RunicArgs<X, unknown[]>): any;
    static tuple<R extends unknown[]>(runes: [...R]): Rune.ValueRune<{
        [K in keyof R]: Rune.T<R[K]>;
    }, Rune.U<R[number]>>;
    static array<T, X>(runes: RunicArgs<X, T[]>): any;
    static fn<A extends any[], T, X>(...[fn]: RunicArgs<X, [(...args: A) => T]>): any;
    static object<R extends {}>(runes: R): Rune.ValueRune<{
        [K in keyof R]: Rune.T<R[K]>;
    }, Rune.U<R[keyof R]>>;
    static captureUnhandled<R extends unknown[], T2, U2>(sources: [...R], fn: (...runes: {
        [K in keyof R]: Rune.ValueRune<Rune.T<R[K]>, never>;
    }) => Rune<T2, U2>): Rune.ValueRune<T2, Rune.U<R[number]> | U2>;
    static asyncIter<T>(fn: (signal: AbortSignal) => AsyncIterable<T>): Rune.ValueRune<T, never>;
    static _placeholder(): Rune<never, never>;
    into<A extends unknown[], C>(ctor: new (_prime: (batch: Batch) => Run<T, U | RunicArgs.U<A>>, ...args: A) => C, ...args: A): C;
    as<R>(this: R, _ctor: new (_prime: (batch: Batch) => Run<T, U>, ...args: any) => R): R;
    unsafeAs<T2, U2 = U>(): Rune<T2, U2>;
    pipe<R extends Rune<any, any>>(fn: (rune: this) => R): R;
}
```

Many of the Rune return types ... `constant`, `str`, `fn`, etc... return `any` as their return types. I think its critical this is fixed before the first release.

**Comment by harrysolovay** [comment] 2023-05-10 18:46
Duplicate of #974

**Closed by harrysolovay** 2023-05-10 18:46 UTC
