### ISSUE TITLE
capi npm `StorageRune.value` returns `any` instead of `ValueRune`

### ISSUE THREAD

**Issue by kratico** [paritytech/capi#981] opened 2023-05-09 18:58 UTC
With `capi@0.1.0-beta.37`, there are several APIs that return `any`

<img width="1038" alt="image" src="https://github.com/paritytech/capi/assets/1209171/d6e5e579-cbd6-4975-bcf4-cac5c98ed6b0">

The `package.json` is similar to 

```
{
  ...,
  "dependencies": {
    "capi": "0.1.0-beta.37",
    "@capi/polkadot": "https://capi.dev/ea4a5fd4b8a3c3aa/polkadot.tar",
    "@capi/polkadot-dev": "https://capi.dev/ea4a5fd4b8a3c3aa/polkadot-dev.tar"
  },
  ...
}
```

**Comment by harrysolovay** [comment] 2023-05-09 21:19
Duplicate of #974

**Closed by harrysolovay** 2023-05-09 21:19 UTC
Labels: bug
