### ISSUE TITLE
xcm teleport assets example JSON parse failures

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#739] opened 2023-03-13 21:44 UTC
Running `xcm_teleport_assets.ts`  sometimes fails with 

```
JSONParseError: Unterminated string in JSON at position 1048576 while parsing '{"relay":[{"name":"alice","wsUri":"ws://'7)
    at ZombienetProvider.network (file:///workspaces/capi/providers/frame/zombienet.ts:46:18)
    at async file:///workspaces/capi/providers/frame/zombienet.ts:33:14
JSONParseError: Unterminated string in JSON at position 1048576 while parsing '{"relay":[{"name":"alice","wsUri":"ws://'
    at ZombienetProvider.network (file:///workspaces/capi/providers/frame/zombienet.ts:46:18)
    at async file:///workspaces/capi/providers/frame/zombienet.ts:33:14
JSONParseError: Unterminated string in JSON at position 1048576 while parsing '{"relay":[{"name":"alice","wsUri":"ws://'
    at ZombienetProvider.network (file:///workspaces/capi/providers/frame/zombienet.ts:46:18)
    at async file:///workspaces/capi/providers/frame/zombienet.ts:33:14
JSONParseError: Unterminated string in JSON at position 1048576 while parsing '{"relay":[{"name":"alice","wsUri":"ws://'
    at ZombienetProvider.network (file:///workspaces/capi/providers/frame/zombienet.ts:46:18)
    at async file:///workspaces/capi/providers/frame/zombienet.ts:33:14
JSONParseError: Unterminated string in JSON at position 1048576 while parsing '{"relay":[{"name":"alice","wsUri":"ws://'
    at ZombienetProvider.network (file:///workspaces/capi/providers/frame/zombienet.ts:46:18)
    at async file:///workspaces/capi/providers/frame/zombienet.ts:33:14
JSONParseError: Unterminated string in JSON at position 1048576 while parsing '{"relay":[{"name":"alice","wsUri":"ws://'
    at ZombienetProvider.network (file:///workspaces/capi/providers/frame/zombienet.ts:46:18)
    at async file:///workspaces/capi/providers/frame/zombienet.ts:33:14
JSONParseError: Unterminated string in JSON at position 1048576 while parsing '{"relay":[{"name":"alice","wsUri":"ws://'
    at ZombienetProvider.network (file:///workspaces/capi/providers/frame/zombienet.ts:46:18)
    at async file:///workspaces/capi/providers/frame/zombienet.ts:33:14
error: Import 'http://localhost:4646/frame/zombienet/zombienets/statemine.toml/alice/@latest/mod.ts' failed: 500 Internal Server Error
    at file:///workspaces/capi/examples/xcm_asset_teleportation.ts:2:34
```

even though the produced JSON is valid (checked by outputing the JSON as a file and running it through https://jsonlint.com/). 

It also works sometimes but its very inconsistent.

**Comment by tjjfvi** [comment] 2023-03-14 12:46
Duplicate of #730

**Closed by tjjfvi** 2023-03-14 12:46 UTC
Labels: bug

**Comment by kratico** [comment] 2023-03-14 12:58
it seems that the modify event is triggered before the file is completely written

https://github.com/paritytech/capi/blob/b8418d0ff2ff659b9d087f7782d7a9a2ee0a1394/providers/frame/zombienet.ts#L40-L49

**Comment by ryanleecode** [comment] 2023-03-14 13:07
Yes that seems to be the likely RC. b.c it did seem like a race condition.
