### ISSUE TITLE
Deno version checks

### ISSUE THREAD

**Issue by wirednkod** [paritytech/capi#820] opened 2023-03-29 09:59 UTC
## Feature Request

It would nice to have some checks on which Deno version should be used in order for CAPI to work;

### Suggestion
```bash
~ deno 
Deno 1.27.1

~ deno task run ./examples/balance.ts
Task run deno task capi -- deno run -A -r=http://localhost:4646/ "./examples/balance.ts"
Task capi deno run -A main.ts "--" "deno" "run" "-A" "-r=http://localhost:4646/" "./examples/balance.ts"
error: Unstable use of npm specifiers. The --unstable flag must be provided.

```

Additional message proposal:
```
Use deno 1.xxx for better compatibility with CAPI
```
or 
```
CAPI supports deno versions >= 1.xxx
```

### Motivation

Trying to run examples with CAPI repo - resulted to the error above - once upgraded to latest version, error disappeared

**Comment by tjjfvi** [comment] 2023-03-29 11:27
There's not really a way for us to detect us as this is an error from Deno during the caching phase, before any of our code is run.

**Comment by wirednkod** [comment] 2023-03-30 14:54
> There's not really a way for us to detect this as this is an error from Deno during the caching phase, before any of our code is run.

Feature says - that it would be nice to provide a minimum version, that devs are testing and knows it works.
I am pretty sure that a check can take place - in order to identify if one runs an older version than recommended;

**Comment by wirednkod** [comment] 2023-03-30 15:35
> The minimum version supported is the latest v1.x – but it could be worthwhile to document that somewhere.

No it is not. As this "feature" mentions, deno 1.27.1 would not actually work; Look at Motivation;

I am not sure why there is a rush to close issues/features/bugs before understanding the reason why they were opened. It is a bit frustrating to me; I cannot understand the rush and the short-responses that provide no value

**Comment by tjjfvi** [comment] 2023-03-30 16:37
Sorry, I meant latest v1.x in an evergreen sense – i.e. 1.32.1 is supported but not 1.27.1. This is fairly common for Deno projects (since Deno is still on major version 1, there haven't been any breaking changes).

I originally closed the issue because the proposed feature – checking the Deno version in the CLI – was infeasible. But since the issue is applicable in the broader context of documenting what versions of Deno we support / considering what versions of Deno we plan to support down the line, it would be good to have an issue. I'll reopen this issue so we'll be sure to follow up.

**Comment by tjjfvi** [comment] 2023-07-10 13:16
I've opened #1154 about documenting our Deno version requirement, so I'm going to close this issue.

**Closed by tjjfvi** 2023-07-10 13:16 UTC
Labels: feature

**Comment by vjjft** [comment] 2023-07-10 15:20
Would it be possible/reasonable for the `deno task capi` script to check the demo version?

**Comment by tjjfvi** [comment] 2023-07-10 17:27
In the case mentioned in this issue, it wouldn't be possible, as it was an error during the caching phase, before our code even ran.

We also don't currently have a fixed supported version of Deno – we only support the latest 1.x version of Deno, so there wouldn't be something fixed to check against.
