### ISSUE TITLE
nesting multisigs

### ISSUE THREAD

**Issue by danielpetroff** [paritytech/capi#398] opened 2022-11-14 11:49 UTC
### Suggestion

An option when setting up a Multisig to allow user to assign a group as a signatory as well as a number of group members who must sign in order to constitute group signature.
Can be used in conjunction with transaction value tiers ([397](https://github.com/paritytech/capi/issues/397))

### Motivation

This is often used for payments that require approval from multiple corporate functions such as Finance, Legal, Compliance, Operations, Business Units, etc...

### Use Cases

A signature is required from Finance, Legal, and Operations

3 groups:
- Finance (F) - 5 members (threshold 2)
- Legal (L) - 4 members (threshold 2)
- Operations (O) - 5 members (threshold 1)

To complete transaction approval, each groups threshold must be met.

This can be used in conjunction with ([397](https://github.com/paritytech/capi/issues/397)) where the above example will be assigned to a tier.

**Comment by tjjfvi** [comment] 2022-11-14 15:44
I believe this can be done already with a multisig of multisigs:
```ts
const finance = multisigAddress([a, b, c, d, e], 2)
const legal = multisigAddress([f, g, h, i], 2)
const operations = multisigAddress([j, k, l, m, n], 1)
const all = multisigAddress([finance, legal, operations], 3)
```

**Comment by danielpetroff** [comment] 2022-11-14 15:59
Yeah, multisig of multisigs is a viable way to achieve that.

**Comment by harrysolovay** [comment] 2022-11-14 18:37
@tjjfvi is correct, this is already doable. This would make for a great tutorial.

**Comment by kratico** [comment] 2022-11-18 14:40
There is also Proxy Accounts https://wiki.polkadot.network/docs/learn-proxies
Using pure proxies will allow to change signatories within multisig accounts

**Comment by ryanleecode** [comment] 2023-02-23 00:39
this is a duplicate of #525 at this point yes? @harrysolovay

**Comment by harrysolovay** [comment] 2023-02-23 10:39
Not quite: I believe this is just about multisig nesting (created #646), not about the interplay of proxies and multisigs. We can close this, as it's already possible (now we just need an example).

**Closed by harrysolovay** 2023-02-23 10:39 UTC
Labels: example
