### ISSUE TITLE
Command `npx capi` does not work

### ISSUE THREAD

**Issue by wirednkod** [paritytech/capi#819] opened 2023-03-29 09:52 UTC
### Current Behavior

Following [this part of the documentation](https://docs.capi.dev/docs/getting_started/overview#with-nodejs) the command `npx capi` does not seem to work; Rather it returns the following:
```bash
➜  npx capi
npm ERR! could not determine executable to run
```

### Expected Behavior

Upon running the command, one should see the message Capi server listening at "http://localhost:4646".

### Steps To Reproduce

run `npx capi`

### Environment

- Node:  v18.14.2

**Comment by tjjfvi** [comment] 2023-03-29 11:19
Yes, CLI is not yet supported on NodeJS; duplicate of #604

**Comment by wirednkod** [comment] 2023-03-29 11:23
It is clearly mentioned [in the documentation](https://docs.capi.dev/docs/getting_started/overview#with-nodejs) that `With NodeJS`; Shouldn't that be removed from the documentation then - and add that CLI is not supported?

Especially when this is closed as "not planned";

**Comment by tjjfvi** [comment] 2023-03-29 11:29
The docs also say:

> The documentation may not reflect the current implementation.

We're pre v0.1.0. And "not planned" in GitHub includes duplicate:
![image](https://user-images.githubusercontent.com/44031566/228521995-0e435ae5-2040-4eae-b2ca-d83b28e07848.png)

**Closed** 2023-03-29 11:31 UTC
Labels: bug, duplicate

**Comment by wirednkod** [comment] 2023-03-29 12:23
> The docs also say:
> 
> > The documentation may not reflect the current implementation.

Where?

**Comment by tjjfvi** [comment] 2023-03-29 12:50
Yes, the README says that, and docs.capi.dev (which is only linked to from the readme) has a large "under construction" disclaimer at the top.

**Comment by wirednkod** [comment] 2023-03-29 13:23
> which is only linked to from the readme)

IMO, the documentation should correspond to the "current running version" - IMO it should not be linked until there is corresponding version. 

We have, a similar approach, with Zombienet documentation (also labeled "under heavy construction") - it may be missing functionalities and/or having some bugs - but what is there, works and devs can follow the docs/tutorials in order to baby-step through it. 

It also has paid off, since people follow it and provide us feedback and/or open issues on discrepancies;

In any case - this is just my feedback and my opinion, and I do not mean to make any harsh judgements or anything similar;

**Comment by tjjfvi** [comment] 2023-03-30 16:39
> IMO, the documentation should correspond to the "current version" - it should not be linked until there is corresponding version.

Agreed, and we'll be following this approach for v0.1.0 and beyond 🙂
